# Generated by Django 5.2 on 2026-03-12 18:35

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('side-hustle', 'Side Hustle'), ('make-money-online', 'Make Money Online'), ('investing', 'Investing'), ('freelancing', 'Freelancing'), ('e-commerce', 'E-Commerce'), ('mindset', 'Mindset'), ('tools', 'Tools & Resources')], max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('excerpt', models.TextField(help_text='Short summary shown on the listing page', max_length=300)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intro_video_url', models.URLField(blank=True, help_text='YouTube or any external video URL for the course intro', null=True)),
                ('external_resource_url', models.URLField(blank=True, help_text='Optional link to a resource, tool, or platform', null=True)),
                ('external_resource_label', models.CharField(blank=True, help_text="Button label for the external resource, e.g. 'Join the Platform'", max_length=100)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('side-hustle', 'Side Hustle'), ('make-money-online', 'Make Money Online'), ('investing', 'Investing'), ('freelancing', 'Freelancing'), ('e-commerce', 'E-Commerce'), ('mindset', 'Mindset'), ('tools', 'Tools & Resources')], max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('excerpt', models.TextField(help_text='Short summary shown on the listing page', max_length=300)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
